name: Actualizar Sponsors
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sponsors:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.SPONSORS_TOKEN }} # Usa tu token para poder guardar los cambios
      
      - name: Obtener Sponsors y actualizar README
        env:
          GH_TOKEN: ${{ secrets.SPONSORS_TOKEN }}
        run: |
          # 1. Consultar la API de GitHub para traer a tus patrocinadores
          HTML_SPONSORS=$(gh api graphql -F login="joguel96" -f query='
            query($login: String!) {
              user(login: $login) {
                sponsorshipsAsMaintainer(first: 100) {
                  nodes {
                    sponsorEntity {
                      ... on User { login, avatarUrl }
                      ... on Organization { login, avatarUrl }
                    }
                  }
                }
              }
            }' --jq '[.data.user.sponsorshipsAsMaintainer.nodes[].sponsorEntity | "<a href=\"https://github.com/\(.login)\"><img src=\"\(.avatarUrl)&s=60\" width=\"60\" style=\"border-radius:50%; margin:5px;\" alt=\"\(.login)\" /></a>"] | join(" ")')
          
          export HTML_SPONSORS
          
          # 2. Insertar los avatares entre las etiquetas HTML de tu README
          perl -0777 -pi -e 's/().*?()/$1\n$ENV{HTML_SPONSORS}\n$2/s' README.md
          
      - name: Guardar y subir cambios
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: actualizar lista de sponsors" || echo "Sin cambios nuevos"
          git push
